/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "status.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SensorChannelData, SensorChannelData, AUTO)


PB_BIND(SensorData, SensorData, AUTO)


PB_BIND(WifiStatus, WifiStatus, AUTO)


PB_BIND(UartData, UartData, AUTO)


PB_BIND(StatusMessage, StatusMessage, AUTO)



